# Generated by Django 3.2 on 2021-11-17 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('string_manipulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationmodel',
            name='string',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='string_manipulation.stringmodel'),
            preserve_default=False,
        ),
    ]
